//
//	This file is automatically generated
//
case 0x06: /**** $06:rlc ($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); temp8 = SRRLC(temp8); WRITE8(temp16,temp8);;
	CYCLES(23);break;

case 0x0e: /**** $0e:rrc ($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); temp8 = SRRRC(temp8); WRITE8(temp16,temp8);;
	CYCLES(23);break;

case 0x16: /**** $16:rl ($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); temp8 = SRRL(temp8); WRITE8(temp16,temp8);;
	CYCLES(23);break;

case 0x1e: /**** $1e:rr ($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); temp8 = SRRR(temp8); WRITE8(temp16,temp8);;
	CYCLES(23);break;

case 0x26: /**** $26:sla ($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); temp8 = SRSLA(temp8); WRITE8(temp16,temp8);;
	CYCLES(23);break;

case 0x2e: /**** $2e:sra ($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); temp8 = SRSRA(temp8); WRITE8(temp16,temp8);;
	CYCLES(23);break;

case 0x3e: /**** $3e:srl ($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); temp8 = SRSRL(temp8); WRITE8(temp16,temp8);;
	CYCLES(23);break;

case 0x46: /**** $46:bit 0,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 1);;
	CYCLES(20);break;

case 0x4e: /**** $4e:bit 1,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 2);;
	CYCLES(20);break;

case 0x56: /**** $56:bit 2,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 4);;
	CYCLES(20);break;

case 0x5e: /**** $5e:bit 3,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 8);;
	CYCLES(20);break;

case 0x66: /**** $66:bit 4,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 16);;
	CYCLES(20);break;

case 0x6e: /**** $6e:bit 5,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 32);;
	CYCLES(20);break;

case 0x76: /**** $76:bit 6,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 64);;
	CYCLES(20);break;

case 0x7e: /**** $7e:bit 7,($i$s) ****/
	temp16 = IZ()+offset; bitOp(READ8(temp16) & 128);;
	CYCLES(20);break;

case 0x86: /**** $86:res 0,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~1));;
	CYCLES(20);break;

case 0x8e: /**** $8e:res 1,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~2));;
	CYCLES(20);break;

case 0x96: /**** $96:res 2,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~4));;
	CYCLES(20);break;

case 0x9e: /**** $9e:res 3,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~8));;
	CYCLES(20);break;

case 0xa6: /**** $a6:res 4,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~16));;
	CYCLES(20);break;

case 0xae: /**** $ae:res 5,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~32));;
	CYCLES(20);break;

case 0xb6: /**** $b6:res 6,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~64));;
	CYCLES(20);break;

case 0xbe: /**** $be:res 7,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8 & (~128));;
	CYCLES(20);break;

case 0xc6: /**** $c6:set 0,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|1);;
	CYCLES(20);break;

case 0xce: /**** $ce:set 1,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|2);;
	CYCLES(20);break;

case 0xd6: /**** $d6:set 2,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|4);;
	CYCLES(20);break;

case 0xde: /**** $de:set 3,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|8);;
	CYCLES(20);break;

case 0xe6: /**** $e6:set 4,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|16);;
	CYCLES(20);break;

case 0xee: /**** $ee:set 5,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|32);;
	CYCLES(20);break;

case 0xf6: /**** $f6:set 6,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|64);;
	CYCLES(20);break;

case 0xfe: /**** $fe:set 7,($i$s) ****/
	temp16 = IZ()+offset; temp8 = READ8(temp16); WRITE8(temp16,temp8|128);;
	CYCLES(20);break;


