//
//	This file is automatically generated
//
case 0x00: /**** $00:nop ****/
	{};
	CYCLES(4);break;

case 0x01: /**** $01:ld bc,$2 ****/
	temp16 = FETCH16(); SETBC(temp16);;
	CYCLES(10);break;

case 0x02: /**** $02:ld (bc),a ****/
	WRITE8(BC(),A);
	CYCLES(7);break;

case 0x03: /**** $03:inc bc ****/
	ZINCBC();
	CYCLES(6);break;

case 0x04: /**** $04:inc b ****/
	ZINC8(B);
	CYCLES(4);break;

case 0x05: /**** $05:dec b ****/
	ZDEC8(B);
	CYCLES(4);break;

case 0x06: /**** $06:ld b,$1 ****/
	B = FETCH8();
	CYCLES(7);break;

case 0x07: /**** $07:rlca ****/
	SETCARRY((A & 0x80) != 0); A = (A << 1) | (A >> 7); SETHALFCARRY(0);SETNFLAG(0);;
	CYCLES(4);break;

case 0x08: /**** $08:ex af,af' ****/
	temp16 = AF();SETAF(AFalt);AFalt = temp16;;
	CYCLES(4);break;

case 0x09: /**** $09:add hl,bc ****/
	temp16 = zAdd16(HL(),BC()); SETHL(temp16);;
	CYCLES(11);break;

case 0x0a: /**** $0a:ld a,(bc) ****/
	A = READ8(BC());
	CYCLES(7);break;

case 0x0b: /**** $0b:dec bc ****/
	ZDECBC();
	CYCLES(6);break;

case 0x0c: /**** $0c:inc c ****/
	ZINC8(C);
	CYCLES(4);break;

case 0x0d: /**** $0d:dec c ****/
	ZDEC8(C);
	CYCLES(4);break;

case 0x0e: /**** $0e:ld c,$1 ****/
	C = FETCH8();
	CYCLES(7);break;

case 0x0f: /**** $0f:rrca ****/
	SETCARRY((A & 0x01) != 0); A = (A >> 1) | (A << 7); SETHALFCARRY(0);SETNFLAG(0);;
	CYCLES(4);break;

case 0x10: /**** $10:djnz $o ****/
	B--;ZJUMPR(B != 0);
	CYCLES(8);break;

case 0x11: /**** $11:ld de,$2 ****/
	temp16 = FETCH16(); SETDE(temp16);;
	CYCLES(10);break;

case 0x12: /**** $12:ld (de),a ****/
	WRITE8(DE(),A);
	CYCLES(7);break;

case 0x13: /**** $13:inc de ****/
	ZINCDE();
	CYCLES(6);break;

case 0x14: /**** $14:inc d ****/
	ZINC8(D);
	CYCLES(4);break;

case 0x15: /**** $15:dec d ****/
	ZDEC8(D);
	CYCLES(4);break;

case 0x16: /**** $16:ld d,$1 ****/
	D = FETCH8();
	CYCLES(7);break;

case 0x17: /**** $17:rla ****/
	temp16 = (A << 1) | (c_Flag ? 1 : 0); SETCARRY((A & 0x80) != 0); A = temp16; SETHALFCARRY(0);SETNFLAG(0);;
	CYCLES(4);break;

case 0x18: /**** $18:jr $o ****/
	ZJUMPR(1);
	CYCLES(7);break;

case 0x19: /**** $19:add hl,de ****/
	temp16 = zAdd16(HL(),DE()); SETHL(temp16);;
	CYCLES(11);break;

case 0x1a: /**** $1a:ld a,(de) ****/
	A = READ8(DE());
	CYCLES(7);break;

case 0x1b: /**** $1b:dec de ****/
	ZDECDE();
	CYCLES(6);break;

case 0x1c: /**** $1c:inc e ****/
	ZINC8(E);
	CYCLES(4);break;

case 0x1d: /**** $1d:dec e ****/
	ZDEC8(E);
	CYCLES(4);break;

case 0x1e: /**** $1e:ld e,$1 ****/
	E = FETCH8();
	CYCLES(7);break;

case 0x1f: /**** $1f:rra ****/
	temp16 = A | (c_Flag ? 0x100 : 0); SETCARRY((A & 0x01) != 0); A = temp16 >> 1; SETHALFCARRY(0);SETNFLAG(0);;
	CYCLES(4);break;

case 0x20: /**** $20:jr nz,$o ****/
	ZJUMPR(TESTNZ());
	CYCLES(7);break;

case 0x21: /**** $21:ld hl,$2 ****/
	temp16 = FETCH16(); SETHL(temp16);;
	CYCLES(10);break;

case 0x22: /**** $22:ld ($2),hl ****/
	temp16 = FETCH16();WRITE16(temp16,HL());
	CYCLES(20);break;

case 0x23: /**** $23:inc hl ****/
	ZINCHL();
	CYCLES(6);break;

case 0x24: /**** $24:inc h ****/
	ZINC8(H);
	CYCLES(4);break;

case 0x25: /**** $25:dec h ****/
	ZDEC8(H);
	CYCLES(4);break;

case 0x26: /**** $26:ld h,$1 ****/
	H = FETCH8();
	CYCLES(7);break;

case 0x27: /**** $27:daa ****/
	zDAA();;
	CYCLES(4);break;

case 0x28: /**** $28:jr z,$o ****/
	ZJUMPR(TESTZ());
	CYCLES(7);break;

case 0x29: /**** $29:add hl,hl ****/
	temp16 = zAdd16(HL(),HL()); SETHL(temp16);;
	CYCLES(11);break;

case 0x2a: /**** $2a:ld hl,($2) ****/
	temp16 = FETCH16();SETHL(READ16(temp16));
	CYCLES(16);break;

case 0x2b: /**** $2b:dec hl ****/
	ZDECHL();
	CYCLES(6);break;

case 0x2c: /**** $2c:inc l ****/
	ZINC8(L);
	CYCLES(4);break;

case 0x2d: /**** $2d:dec l ****/
	ZDEC8(L);
	CYCLES(4);break;

case 0x2e: /**** $2e:ld l,$1 ****/
	L = FETCH8();
	CYCLES(7);break;

case 0x2f: /**** $2f:cpl ****/
	A = A ^ 0xFF; SETHALFCARRY(1); SETNFLAG(1);;
	CYCLES(4);break;

case 0x30: /**** $30:jr nc,$o ****/
	ZJUMPR(TESTNC());
	CYCLES(7);break;

case 0x31: /**** $31:ld sp,$2 ****/
	temp16 = FETCH16(); SETSP(temp16);;
	CYCLES(10);break;

case 0x32: /**** $32:ld ($2),a ****/
	WRITE8(FETCH16(),A);
	CYCLES(13);break;

case 0x33: /**** $33:inc sp ****/
	ZINCSP();
	CYCLES(6);break;

case 0x34: /**** $34:inc (hl) ****/
	temp8 = READ8(HL()); ZINC8(temp8); WRITE8(HL(),temp8);;
	CYCLES(11);break;

case 0x35: /**** $35:dec (hl) ****/
	temp8 = READ8(HL()); ZDEC8(temp8); WRITE8(HL(),temp8);;
	CYCLES(11);break;

case 0x36: /**** $36:ld (hl),$1 ****/
	WRITE8(HL(),FETCH8());
	CYCLES(7);break;

case 0x37: /**** $37:scf ****/
	SETCARRY(1); SETHALFCARRY(0); SETNFLAG(0);;
	CYCLES(4);break;

case 0x38: /**** $38:jr c,$o ****/
	ZJUMPR(TESTC());
	CYCLES(7);break;

case 0x39: /**** $39:add hl,sp ****/
	temp16 = zAdd16(HL(),SP()); SETHL(temp16);;
	CYCLES(11);break;

case 0x3a: /**** $3a:ld a,($2) ****/
	A = READ8(FETCH16());;
	CYCLES(13);break;

case 0x3b: /**** $3b:dec sp ****/
	ZDECSP();
	CYCLES(6);break;

case 0x3c: /**** $3c:inc a ****/
	ZINC8(A);
	CYCLES(4);break;

case 0x3d: /**** $3d:dec a ****/
	ZDEC8(A);
	CYCLES(4);break;

case 0x3e: /**** $3e:ld a,$1 ****/
	A = FETCH8();
	CYCLES(7);break;

case 0x3f: /**** $3f:ccf ****/
	SETHALFCARRY(c_Flag); SETCARRY(c_Flag == 0); SETNFLAG(0);;
	CYCLES(4);break;

case 0x40: /**** $40:ld b,b ****/
	B = B;
	CYCLES(4);break;

case 0x41: /**** $41:ld b,c ****/
	B = C;
	CYCLES(4);break;

case 0x42: /**** $42:ld b,d ****/
	B = D;
	CYCLES(4);break;

case 0x43: /**** $43:ld b,e ****/
	B = E;
	CYCLES(4);break;

case 0x44: /**** $44:ld b,h ****/
	B = H;
	CYCLES(4);break;

case 0x45: /**** $45:ld b,l ****/
	B = L;
	CYCLES(4);break;

case 0x46: /**** $46:ld b,(hl) ****/
	B = READ8(HL());
	CYCLES(4);break;

case 0x47: /**** $47:ld b,a ****/
	B = A;
	CYCLES(4);break;

case 0x48: /**** $48:ld c,b ****/
	C = B;
	CYCLES(4);break;

case 0x49: /**** $49:ld c,c ****/
	C = C;
	CYCLES(4);break;

case 0x4a: /**** $4a:ld c,d ****/
	C = D;
	CYCLES(4);break;

case 0x4b: /**** $4b:ld c,e ****/
	C = E;
	CYCLES(4);break;

case 0x4c: /**** $4c:ld c,h ****/
	C = H;
	CYCLES(4);break;

case 0x4d: /**** $4d:ld c,l ****/
	C = L;
	CYCLES(4);break;

case 0x4e: /**** $4e:ld c,(hl) ****/
	C = READ8(HL());
	CYCLES(4);break;

case 0x4f: /**** $4f:ld c,a ****/
	C = A;
	CYCLES(4);break;

case 0x50: /**** $50:ld d,b ****/
	D = B;
	CYCLES(4);break;

case 0x51: /**** $51:ld d,c ****/
	D = C;
	CYCLES(4);break;

case 0x52: /**** $52:ld d,d ****/
	D = D;
	CYCLES(4);break;

case 0x53: /**** $53:ld d,e ****/
	D = E;
	CYCLES(4);break;

case 0x54: /**** $54:ld d,h ****/
	D = H;
	CYCLES(4);break;

case 0x55: /**** $55:ld d,l ****/
	D = L;
	CYCLES(4);break;

case 0x56: /**** $56:ld d,(hl) ****/
	D = READ8(HL());
	CYCLES(4);break;

case 0x57: /**** $57:ld d,a ****/
	D = A;
	CYCLES(4);break;

case 0x58: /**** $58:ld e,b ****/
	E = B;
	CYCLES(4);break;

case 0x59: /**** $59:ld e,c ****/
	E = C;
	CYCLES(4);break;

case 0x5a: /**** $5a:ld e,d ****/
	E = D;
	CYCLES(4);break;

case 0x5b: /**** $5b:ld e,e ****/
	E = E;
	CYCLES(4);break;

case 0x5c: /**** $5c:ld e,h ****/
	E = H;
	CYCLES(4);break;

case 0x5d: /**** $5d:ld e,l ****/
	E = L;
	CYCLES(4);break;

case 0x5e: /**** $5e:ld e,(hl) ****/
	E = READ8(HL());
	CYCLES(4);break;

case 0x5f: /**** $5f:ld e,a ****/
	E = A;
	CYCLES(4);break;

case 0x60: /**** $60:ld h,b ****/
	H = B;
	CYCLES(4);break;

case 0x61: /**** $61:ld h,c ****/
	H = C;
	CYCLES(4);break;

case 0x62: /**** $62:ld h,d ****/
	H = D;
	CYCLES(4);break;

case 0x63: /**** $63:ld h,e ****/
	H = E;
	CYCLES(4);break;

case 0x64: /**** $64:ld h,h ****/
	H = H;
	CYCLES(4);break;

case 0x65: /**** $65:ld h,l ****/
	H = L;
	CYCLES(4);break;

case 0x66: /**** $66:ld h,(hl) ****/
	H = READ8(HL());
	CYCLES(4);break;

case 0x67: /**** $67:ld h,a ****/
	H = A;
	CYCLES(4);break;

case 0x68: /**** $68:ld l,b ****/
	L = B;
	CYCLES(4);break;

case 0x69: /**** $69:ld l,c ****/
	L = C;
	CYCLES(4);break;

case 0x6a: /**** $6a:ld l,d ****/
	L = D;
	CYCLES(4);break;

case 0x6b: /**** $6b:ld l,e ****/
	L = E;
	CYCLES(4);break;

case 0x6c: /**** $6c:ld l,h ****/
	L = H;
	CYCLES(4);break;

case 0x6d: /**** $6d:ld l,l ****/
	L = L;
	CYCLES(4);break;

case 0x6e: /**** $6e:ld l,(hl) ****/
	L = READ8(HL());
	CYCLES(4);break;

case 0x6f: /**** $6f:ld l,a ****/
	L = A;
	CYCLES(4);break;

case 0x70: /**** $70:ld (hl),b ****/
	WRITE8(HL(),B);
	CYCLES(7);break;

case 0x71: /**** $71:ld (hl),c ****/
	WRITE8(HL(),C);
	CYCLES(7);break;

case 0x72: /**** $72:ld (hl),d ****/
	WRITE8(HL(),D);
	CYCLES(7);break;

case 0x73: /**** $73:ld (hl),e ****/
	WRITE8(HL(),E);
	CYCLES(7);break;

case 0x74: /**** $74:ld (hl),h ****/
	WRITE8(HL(),H);
	CYCLES(7);break;

case 0x75: /**** $75:ld (hl),l ****/
	WRITE8(HL(),L);
	CYCLES(7);break;

case 0x76: /**** $76:halt ****/
	PC--;
	CYCLES(255);break;

case 0x77: /**** $77:ld (hl),a ****/
	WRITE8(HL(),A);
	CYCLES(7);break;

case 0x78: /**** $78:ld a,b ****/
	A = B;
	CYCLES(4);break;

case 0x79: /**** $79:ld a,c ****/
	A = C;
	CYCLES(4);break;

case 0x7a: /**** $7a:ld a,d ****/
	A = D;
	CYCLES(4);break;

case 0x7b: /**** $7b:ld a,e ****/
	A = E;
	CYCLES(4);break;

case 0x7c: /**** $7c:ld a,h ****/
	A = H;
	CYCLES(4);break;

case 0x7d: /**** $7d:ld a,l ****/
	A = L;
	CYCLES(4);break;

case 0x7e: /**** $7e:ld a,(hl) ****/
	A = READ8(HL());
	CYCLES(4);break;

case 0x7f: /**** $7f:ld a,a ****/
	A = A;
	CYCLES(4);break;

case 0x80: /**** $80:add b ****/
	ZALUADD(B);
	CYCLES(4);break;

case 0x81: /**** $81:add c ****/
	ZALUADD(C);
	CYCLES(4);break;

case 0x82: /**** $82:add d ****/
	ZALUADD(D);
	CYCLES(4);break;

case 0x83: /**** $83:add e ****/
	ZALUADD(E);
	CYCLES(4);break;

case 0x84: /**** $84:add h ****/
	ZALUADD(H);
	CYCLES(4);break;

case 0x85: /**** $85:add l ****/
	ZALUADD(L);
	CYCLES(4);break;

case 0x86: /**** $86:add (hl) ****/
	ZALUADD(READ8(HL()));
	CYCLES(4);break;

case 0x87: /**** $87:add a ****/
	ZALUADD(A);
	CYCLES(4);break;

case 0x88: /**** $88:adc b ****/
	ZALUADC(B);
	CYCLES(4);break;

case 0x89: /**** $89:adc c ****/
	ZALUADC(C);
	CYCLES(4);break;

case 0x8a: /**** $8a:adc d ****/
	ZALUADC(D);
	CYCLES(4);break;

case 0x8b: /**** $8b:adc e ****/
	ZALUADC(E);
	CYCLES(4);break;

case 0x8c: /**** $8c:adc h ****/
	ZALUADC(H);
	CYCLES(4);break;

case 0x8d: /**** $8d:adc l ****/
	ZALUADC(L);
	CYCLES(4);break;

case 0x8e: /**** $8e:adc (hl) ****/
	ZALUADC(READ8(HL()));
	CYCLES(4);break;

case 0x8f: /**** $8f:adc a ****/
	ZALUADC(A);
	CYCLES(4);break;

case 0x90: /**** $90:sub b ****/
	ZALUSUB(B);
	CYCLES(4);break;

case 0x91: /**** $91:sub c ****/
	ZALUSUB(C);
	CYCLES(4);break;

case 0x92: /**** $92:sub d ****/
	ZALUSUB(D);
	CYCLES(4);break;

case 0x93: /**** $93:sub e ****/
	ZALUSUB(E);
	CYCLES(4);break;

case 0x94: /**** $94:sub h ****/
	ZALUSUB(H);
	CYCLES(4);break;

case 0x95: /**** $95:sub l ****/
	ZALUSUB(L);
	CYCLES(4);break;

case 0x96: /**** $96:sub (hl) ****/
	ZALUSUB(READ8(HL()));
	CYCLES(4);break;

case 0x97: /**** $97:sub a ****/
	ZALUSUB(A);
	CYCLES(4);break;

case 0x98: /**** $98:sbc b ****/
	ZALUSBC(B);
	CYCLES(4);break;

case 0x99: /**** $99:sbc c ****/
	ZALUSBC(C);
	CYCLES(4);break;

case 0x9a: /**** $9a:sbc d ****/
	ZALUSBC(D);
	CYCLES(4);break;

case 0x9b: /**** $9b:sbc e ****/
	ZALUSBC(E);
	CYCLES(4);break;

case 0x9c: /**** $9c:sbc h ****/
	ZALUSBC(H);
	CYCLES(4);break;

case 0x9d: /**** $9d:sbc l ****/
	ZALUSBC(L);
	CYCLES(4);break;

case 0x9e: /**** $9e:sbc (hl) ****/
	ZALUSBC(READ8(HL()));
	CYCLES(4);break;

case 0x9f: /**** $9f:sbc a ****/
	ZALUSBC(A);
	CYCLES(4);break;

case 0xa0: /**** $a0:and b ****/
	ZALUAND(B);
	CYCLES(4);break;

case 0xa1: /**** $a1:and c ****/
	ZALUAND(C);
	CYCLES(4);break;

case 0xa2: /**** $a2:and d ****/
	ZALUAND(D);
	CYCLES(4);break;

case 0xa3: /**** $a3:and e ****/
	ZALUAND(E);
	CYCLES(4);break;

case 0xa4: /**** $a4:and h ****/
	ZALUAND(H);
	CYCLES(4);break;

case 0xa5: /**** $a5:and l ****/
	ZALUAND(L);
	CYCLES(4);break;

case 0xa6: /**** $a6:and (hl) ****/
	ZALUAND(READ8(HL()));
	CYCLES(4);break;

case 0xa7: /**** $a7:and a ****/
	ZALUAND(A);
	CYCLES(4);break;

case 0xa8: /**** $a8:xor b ****/
	ZALUXOR(B);
	CYCLES(4);break;

case 0xa9: /**** $a9:xor c ****/
	ZALUXOR(C);
	CYCLES(4);break;

case 0xaa: /**** $aa:xor d ****/
	ZALUXOR(D);
	CYCLES(4);break;

case 0xab: /**** $ab:xor e ****/
	ZALUXOR(E);
	CYCLES(4);break;

case 0xac: /**** $ac:xor h ****/
	ZALUXOR(H);
	CYCLES(4);break;

case 0xad: /**** $ad:xor l ****/
	ZALUXOR(L);
	CYCLES(4);break;

case 0xae: /**** $ae:xor (hl) ****/
	ZALUXOR(READ8(HL()));
	CYCLES(4);break;

case 0xaf: /**** $af:xor a ****/
	ZALUXOR(A);
	CYCLES(4);break;

case 0xb0: /**** $b0:or b ****/
	ZALUOR(B);
	CYCLES(4);break;

case 0xb1: /**** $b1:or c ****/
	ZALUOR(C);
	CYCLES(4);break;

case 0xb2: /**** $b2:or d ****/
	ZALUOR(D);
	CYCLES(4);break;

case 0xb3: /**** $b3:or e ****/
	ZALUOR(E);
	CYCLES(4);break;

case 0xb4: /**** $b4:or h ****/
	ZALUOR(H);
	CYCLES(4);break;

case 0xb5: /**** $b5:or l ****/
	ZALUOR(L);
	CYCLES(4);break;

case 0xb6: /**** $b6:or (hl) ****/
	ZALUOR(READ8(HL()));
	CYCLES(4);break;

case 0xb7: /**** $b7:or a ****/
	ZALUOR(A);
	CYCLES(4);break;

case 0xb8: /**** $b8:cp b ****/
	ZALUCP(B);
	CYCLES(4);break;

case 0xb9: /**** $b9:cp c ****/
	ZALUCP(C);
	CYCLES(4);break;

case 0xba: /**** $ba:cp d ****/
	ZALUCP(D);
	CYCLES(4);break;

case 0xbb: /**** $bb:cp e ****/
	ZALUCP(E);
	CYCLES(4);break;

case 0xbc: /**** $bc:cp h ****/
	ZALUCP(H);
	CYCLES(4);break;

case 0xbd: /**** $bd:cp l ****/
	ZALUCP(L);
	CYCLES(4);break;

case 0xbe: /**** $be:cp (hl) ****/
	ZALUCP(READ8(HL()));
	CYCLES(4);break;

case 0xbf: /**** $bf:cp a ****/
	ZALUCP(A);
	CYCLES(4);break;

case 0xc0: /**** $c0:ret nz ****/
	ZRETURN(TESTNZ());
	CYCLES(5);break;

case 0xc1: /**** $c1:pop bc ****/
	temp16 = ZPOP();SETBC(temp16);
	CYCLES(10);break;

case 0xc2: /**** $c2:jp nz,$2 ****/
	ZJUMP(TESTNZ());
	CYCLES(10);break;

case 0xc3: /**** $c3:jp $2 ****/
	ZJUMP(1);
	CYCLES(10);break;

case 0xc4: /**** $c4:call nz,$2 ****/
	ZCALL(TESTNZ());
	CYCLES(10);break;

case 0xc5: /**** $c5:push bc ****/
	ZPUSH(BC());
	CYCLES(11);break;

case 0xc6: /**** $c6:add $1 ****/
	ZALUADD(FETCH8());
	CYCLES(7);break;

case 0xc7: /**** $c7:rst 00 ****/
	ZPUSH(PC);PC = 0x00;;
	CYCLES(11);break;

case 0xc8: /**** $c8:ret z ****/
	ZRETURN(TESTZ());
	CYCLES(5);break;

case 0xc9: /**** $c9:ret ****/
	ZRETURN(1);
	CYCLES(4);break;

case 0xca: /**** $ca:jp z,$2 ****/
	ZJUMP(TESTZ());
	CYCLES(10);break;

case 0xcb: /**** $cb:[cb] ****/
	ExecuteCBGroup();;
	CYCLES(0);break;

case 0xcc: /**** $cc:call z,$2 ****/
	ZCALL(TESTZ());
	CYCLES(10);break;

case 0xcd: /**** $cd:call $2 ****/
	ZCALL(1);
	CYCLES(10);break;

case 0xce: /**** $ce:adc $1 ****/
	ZALUADC(FETCH8());
	CYCLES(7);break;

case 0xcf: /**** $cf:rst 08 ****/
	ZPUSH(PC);PC = 0x08;;
	CYCLES(11);break;

case 0xd0: /**** $d0:ret nc ****/
	ZRETURN(TESTNC());
	CYCLES(5);break;

case 0xd1: /**** $d1:pop de ****/
	temp16 = ZPOP();SETDE(temp16);
	CYCLES(10);break;

case 0xd2: /**** $d2:jp nc,$2 ****/
	ZJUMP(TESTNC());
	CYCLES(10);break;

case 0xd3: /**** $d3:out ($1),a ****/
	temp8 = FETCH8(); OUTPORT(temp8,A);
	CYCLES(11);break;

case 0xd4: /**** $d4:call nc,$2 ****/
	ZCALL(TESTNC());
	CYCLES(10);break;

case 0xd5: /**** $d5:push de ****/
	ZPUSH(DE());
	CYCLES(11);break;

case 0xd6: /**** $d6:sub $1 ****/
	ZALUSUB(FETCH8());
	CYCLES(7);break;

case 0xd7: /**** $d7:rst 10 ****/
	ZPUSH(PC);PC = 0x10;;
	CYCLES(11);break;

case 0xd8: /**** $d8:ret c ****/
	ZRETURN(TESTC());
	CYCLES(5);break;

case 0xd9: /**** $d9:exx ****/
	temp16 = BC();SETBC(BCalt);BCalt = temp16; temp16 = DE();SETDE(DEalt);DEalt = temp16; temp16 = HL();SETHL(HLalt);HLalt = temp16;;
	CYCLES(4);break;

case 0xda: /**** $da:jp c,$2 ****/
	ZJUMP(TESTC());
	CYCLES(10);break;

case 0xdb: /**** $db:in a,($1) ****/
	temp8 = FETCH8(); A = INPORT((A << 8)|temp8);
	CYCLES(11);break;

case 0xdc: /**** $dc:call c,$2 ****/
	ZCALL(TESTC());
	CYCLES(10);break;

case 0xdd: /**** $dd:[ix] ****/
	pIXY = &IX; ExecuteDDGroup();;
	CYCLES(0);break;

case 0xde: /**** $de:sbc $1 ****/
	ZALUSBC(FETCH8());
	CYCLES(7);break;

case 0xdf: /**** $df:rst 18 ****/
	ZPUSH(PC);PC = 0x18;;
	CYCLES(11);break;

case 0xe0: /**** $e0:ret po ****/
	ZRETURN(TESTPO());
	CYCLES(5);break;

case 0xe1: /**** $e1:pop hl ****/
	temp16 = ZPOP();SETHL(temp16);
	CYCLES(10);break;

case 0xe2: /**** $e2:jp po,$2 ****/
	ZJUMP(TESTPO());
	CYCLES(10);break;

case 0xe3: /**** $e3:ex (sp),hl ****/
	temp16 = READ16(SP);temp16a = HL(); WRITE16(SP,temp16a);SETHL(temp16);;
	CYCLES(19);break;

case 0xe4: /**** $e4:call po,$2 ****/
	ZCALL(TESTPO());
	CYCLES(10);break;

case 0xe5: /**** $e5:push hl ****/
	ZPUSH(HL());
	CYCLES(11);break;

case 0xe6: /**** $e6:and $1 ****/
	ZALUAND(FETCH8());
	CYCLES(7);break;

case 0xe7: /**** $e7:rst 20 ****/
	ZPUSH(PC);PC = 0x20;;
	CYCLES(11);break;

case 0xe8: /**** $e8:ret pe ****/
	ZRETURN(TESTPE());
	CYCLES(5);break;

case 0xe9: /**** $e9:jp (hl) ****/
	PC = HL();
	CYCLES(4);break;

case 0xea: /**** $ea:jp pe,$2 ****/
	ZJUMP(TESTPE());
	CYCLES(10);break;

case 0xeb: /**** $eb:ex de,hl ****/
	temp16 = DE();temp16a = HL(); SETDE(temp16a);SETHL(temp16);;
	CYCLES(4);break;

case 0xec: /**** $ec:call pe,$2 ****/
	ZCALL(TESTPE());
	CYCLES(10);break;

case 0xed: /**** $ed:[ed] ****/
	ExecuteEDGroup();;
	CYCLES(0);break;

case 0xee: /**** $ee:xor $1 ****/
	ZALUXOR(FETCH8());
	CYCLES(7);break;

case 0xef: /**** $ef:rst 28 ****/
	ZPUSH(PC);PC = 0x28;;
	CYCLES(11);break;

case 0xf0: /**** $f0:ret p ****/
	ZRETURN(TESTP());
	CYCLES(5);break;

case 0xf1: /**** $f1:pop af ****/
	temp16 = ZPOP();SETAF(temp16);
	CYCLES(10);break;

case 0xf2: /**** $f2:jp p,$2 ****/
	ZJUMP(TESTP());
	CYCLES(10);break;

case 0xf3: /**** $f3:di ****/
	intEnabled = 0;
	CYCLES(4);break;

case 0xf4: /**** $f4:call p,$2 ****/
	ZCALL(TESTP());
	CYCLES(10);break;

case 0xf5: /**** $f5:push af ****/
	ZPUSH(AF());
	CYCLES(11);break;

case 0xf6: /**** $f6:or $1 ****/
	ZALUOR(FETCH8());
	CYCLES(7);break;

case 0xf7: /**** $f7:rst 30 ****/
	ZPUSH(PC);PC = 0x30;;
	CYCLES(11);break;

case 0xf8: /**** $f8:ret m ****/
	ZRETURN(TESTM());
	CYCLES(5);break;

case 0xf9: /**** $f9:ld sp,hl ****/
	SETSP(HL());
	CYCLES(6);break;

case 0xfa: /**** $fa:jp m,$2 ****/
	ZJUMP(TESTM());
	CYCLES(10);break;

case 0xfb: /**** $fb:ei ****/
	intEnabled = 1;
	CYCLES(4);break;

case 0xfc: /**** $fc:call m,$2 ****/
	ZCALL(TESTM());
	CYCLES(10);break;

case 0xfd: /**** $fd:[iy] ****/
	pIXY = &IY; ExecuteDDGroup();;
	CYCLES(0);break;

case 0xfe: /**** $fe:cp $1 ****/
	ZALUCP(FETCH8());
	CYCLES(7);break;

case 0xff: /**** $ff:rst 38 ****/
	ZPUSH(PC);PC = 0x38;;
	CYCLES(11);break;


