//
//	This file is automatically generated
//
case 0x01: /**** $01:ora $1.x ****/
	temp16 = EACABSX(); CALUORA();
	CYCLES(4);break;

case 0x05: /**** $05:ora $1 ****/
	temp16 = EACZERO(); CALUORA();
	CYCLES(4);break;

case 0x06: /**** $06:asl $1 ****/
	temp16 = EACZERO(); temp8 = READ8(temp16); temp8 = CASL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x09: /**** $09:ora $1 ****/
	temp16 = EACIMM(); CALUORA();
	CYCLES(4);break;

case 0x0a: /**** $0a:asl a ****/
	A = CASL(A);
	CYCLES(2);break;

case 0x0d: /**** $0d:ora $2 ****/
	temp16 = EACABS(); CALUORA();
	CYCLES(4);break;

case 0x0e: /**** $0e:asl $2 ****/
	temp16 = EACABS(); temp8 = READ8(temp16); temp8 = CASL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x11: /**** $11:ora ($1).y ****/
	temp16 = EACINDY(); CALUORA();
	CYCLES(4);break;

case 0x12: /**** $12:ora ($1) ****/
	temp16 = EACIND(); CALUORA();
	CYCLES(4);break;

case 0x15: /**** $15:ora $1.x ****/
	temp16 = EACZEROX(); CALUORA();
	CYCLES(4);break;

case 0x16: /**** $16:asl $1.x ****/
	temp16 = EACZEROX(); temp8 = READ8(temp16); temp8 = CASL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x19: /**** $19:ora $2.y ****/
	temp16 = EACABSY(); CALUORA();
	CYCLES(4);break;

case 0x1a: /**** $1a:inc a ****/
	A = CINC(A);
	CYCLES(2);break;

case 0x1d: /**** $1d:ora $2.x ****/
	temp16 = EACABSX(); CALUORA();
	CYCLES(4);break;

case 0x1e: /**** $1e:asl $2.x ****/
	temp16 = EACABSX(); temp8 = READ8(temp16); temp8 = CASL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x21: /**** $21:and $1.x ****/
	temp16 = EACABSX(); CALUAND();
	CYCLES(4);break;

case 0x24: /**** $24:bit $1 ****/
	temp16 = EACZERO(); CBIT(READ8(temp16));;
	CYCLES(2);break;

case 0x25: /**** $25:and $1 ****/
	temp16 = EACZERO(); CALUAND();
	CYCLES(4);break;

case 0x26: /**** $26:rol $1 ****/
	temp16 = EACZERO(); temp8 = READ8(temp16); temp8 = CROL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x29: /**** $29:and $1 ****/
	temp16 = EACIMM(); CALUAND();
	CYCLES(4);break;

case 0x2a: /**** $2a:rol a ****/
	A = CROL(A);
	CYCLES(2);break;

case 0x2c: /**** $2c:bit $2 ****/
	temp16 = EACABS(); CBIT(READ8(temp16));;
	CYCLES(2);break;

case 0x2d: /**** $2d:and $2 ****/
	temp16 = EACABS(); CALUAND();
	CYCLES(4);break;

case 0x2e: /**** $2e:rol $2 ****/
	temp16 = EACABS(); temp8 = READ8(temp16); temp8 = CROL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x31: /**** $31:and ($1).y ****/
	temp16 = EACINDY(); CALUAND();
	CYCLES(4);break;

case 0x32: /**** $32:and ($1) ****/
	temp16 = EACIND(); CALUAND();
	CYCLES(4);break;

case 0x34: /**** $34:bit $1.x ****/
	temp16 = EACZEROX(); CBIT(READ8(temp16));;
	CYCLES(2);break;

case 0x35: /**** $35:and $1.x ****/
	temp16 = EACZEROX(); CALUAND();
	CYCLES(4);break;

case 0x36: /**** $36:rol $1.x ****/
	temp16 = EACZEROX(); temp8 = READ8(temp16); temp8 = CROL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x39: /**** $39:and $2.y ****/
	temp16 = EACABSY(); CALUAND();
	CYCLES(4);break;

case 0x3a: /**** $3a:dec a ****/
	A = CDEC(A);
	CYCLES(2);break;

case 0x3c: /**** $3c:bit $1.y ****/
	temp16 = EACABSX(); CBIT(READ8(temp16));;
	CYCLES(2);break;

case 0x3d: /**** $3d:and $2.x ****/
	temp16 = EACABSX(); CALUAND();
	CYCLES(4);break;

case 0x3e: /**** $3e:rol $2.x ****/
	temp16 = EACABSX(); temp8 = READ8(temp16); temp8 = CROL(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x41: /**** $41:eor $1.x ****/
	temp16 = EACABSX(); CALUEOR();
	CYCLES(4);break;

case 0x45: /**** $45:eor $1 ****/
	temp16 = EACZERO(); CALUEOR();
	CYCLES(4);break;

case 0x46: /**** $46:lsr $1 ****/
	temp16 = EACZERO(); temp8 = READ8(temp16); temp8 = CLSR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x49: /**** $49:eor $1 ****/
	temp16 = EACIMM(); CALUEOR();
	CYCLES(4);break;

case 0x4a: /**** $4a:lsr a ****/
	A = CLSR(A);
	CYCLES(2);break;

case 0x4d: /**** $4d:eor $2 ****/
	temp16 = EACABS(); CALUEOR();
	CYCLES(4);break;

case 0x4e: /**** $4e:lsr $2 ****/
	temp16 = EACABS(); temp8 = READ8(temp16); temp8 = CLSR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x51: /**** $51:eor ($1).y ****/
	temp16 = EACINDY(); CALUEOR();
	CYCLES(4);break;

case 0x52: /**** $52:eor ($1) ****/
	temp16 = EACIND(); CALUEOR();
	CYCLES(4);break;

case 0x55: /**** $55:eor $1.x ****/
	temp16 = EACZEROX(); CALUEOR();
	CYCLES(4);break;

case 0x56: /**** $56:lsr $1.x ****/
	temp16 = EACZEROX(); temp8 = READ8(temp16); temp8 = CLSR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x59: /**** $59:eor $2.y ****/
	temp16 = EACABSY(); CALUEOR();
	CYCLES(4);break;

case 0x5d: /**** $5d:eor $2.x ****/
	temp16 = EACABSX(); CALUEOR();
	CYCLES(4);break;

case 0x5e: /**** $5e:lsr $2.x ****/
	temp16 = EACABSX(); temp8 = READ8(temp16); temp8 = CLSR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x61: /**** $61:adc $1.x ****/
	temp16 = EACABSX(); CALUADC();
	CYCLES(4);break;

case 0x64: /**** $64:stz $1 ****/
	temp16 = EACZERO(); WRITE8(temp16,0);
	CYCLES(2);break;

case 0x65: /**** $65:adc $1 ****/
	temp16 = EACZERO(); CALUADC();
	CYCLES(4);break;

case 0x66: /**** $66:ror $1 ****/
	temp16 = EACZERO(); temp8 = READ8(temp16); temp8 = CROR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x69: /**** $69:adc $1 ****/
	temp16 = EACIMM(); CALUADC();
	CYCLES(4);break;

case 0x6a: /**** $6a:ror a ****/
	A = CROR(A);
	CYCLES(2);break;

case 0x6d: /**** $6d:adc $2 ****/
	temp16 = EACABS(); CALUADC();
	CYCLES(4);break;

case 0x6e: /**** $6e:ror $2 ****/
	temp16 = EACABS(); temp8 = READ8(temp16); temp8 = CROR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x71: /**** $71:adc ($1).y ****/
	temp16 = EACINDY(); CALUADC();
	CYCLES(4);break;

case 0x72: /**** $72:adc ($1) ****/
	temp16 = EACIND(); CALUADC();
	CYCLES(4);break;

case 0x74: /**** $74:stz $1.x ****/
	temp16 = EACZEROX(); WRITE8(temp16,0);
	CYCLES(2);break;

case 0x75: /**** $75:adc $1.x ****/
	temp16 = EACZEROX(); CALUADC();
	CYCLES(4);break;

case 0x76: /**** $76:ror $1.x ****/
	temp16 = EACZEROX(); temp8 = READ8(temp16); temp8 = CROR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x79: /**** $79:adc $2.y ****/
	temp16 = EACABSY(); CALUADC();
	CYCLES(4);break;

case 0x7d: /**** $7d:adc $2.x ****/
	temp16 = EACABSX(); CALUADC();
	CYCLES(4);break;

case 0x7e: /**** $7e:ror $2.x ****/
	temp16 = EACABSX(); temp8 = READ8(temp16); temp8 = CROR(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0x81: /**** $81:sta $1.x ****/
	temp16 = EACABSX(); WRITE16(temp16,A);
	CYCLES(4);break;

case 0x84: /**** $84:sty $1 ****/
	temp16 = EACZERO(); WRITE8(temp16,Y);;
	CYCLES(2);break;

case 0x85: /**** $85:sta $1 ****/
	temp16 = EACZERO(); WRITE16(temp16,A);
	CYCLES(4);break;

case 0x86: /**** $86:stx $1 ****/
	temp16 = EACZERO(); WRITE8(temp16,X);;
	CYCLES(2);break;

case 0x89: /**** $89:bit $1 ****/
	temp16 = EACIMM(); CBIT(READ8(temp16));;
	CYCLES(2);break;

case 0x8c: /**** $8c:sty $2 ****/
	temp16 = EACABS(); WRITE8(temp16,Y);;
	CYCLES(2);break;

case 0x8d: /**** $8d:sta $2 ****/
	temp16 = EACABS(); WRITE16(temp16,A);
	CYCLES(4);break;

case 0x8e: /**** $8e:stx $2 ****/
	temp16 = EACABS(); WRITE8(temp16,X);;
	CYCLES(2);break;

case 0x91: /**** $91:sta ($1).y ****/
	temp16 = EACINDY(); WRITE16(temp16,A);
	CYCLES(4);break;

case 0x94: /**** $94:sty $1.x ****/
	temp16 = EACZEROX(); WRITE8(temp16,Y);;
	CYCLES(2);break;

case 0x95: /**** $95:sta $1.x ****/
	temp16 = EACZEROX(); WRITE16(temp16,A);
	CYCLES(4);break;

case 0x96: /**** $96:stx $1,y ****/
	temp16 = EACZEROY(); WRITE8(temp16,X);;
	CYCLES(2);break;

case 0x99: /**** $99:sta $2.y ****/
	temp16 = EACABSY(); WRITE16(temp16,A);
	CYCLES(4);break;

case 0x9c: /**** $9c:stz $2 ****/
	temp16 = EACZERO(); WRITE8(temp16,0);
	CYCLES(2);break;

case 0x9d: /**** $9d:sta $2.x ****/
	temp16 = EACABSX(); WRITE16(temp16,A);
	CYCLES(4);break;

case 0x9e: /**** $9e:stz $2,x ****/
	temp16 = EACZEROX(); WRITE8(temp16,0);
	CYCLES(2);break;

case 0xa1: /**** $a1:lda $1.x ****/
	temp16 = EACABSX(); CALULDA();
	CYCLES(4);break;

case 0xa2: /**** $a2:ldx $1 ****/
	temp16 = EACIMM(); X = READ8(temp16);;
	CYCLES(2);break;

case 0xa5: /**** $a5:lda $1 ****/
	temp16 = EACZERO(); CALULDA();
	CYCLES(4);break;

case 0xa6: /**** $a6:ldx $1 ****/
	temp16 = EACZERO(); X = READ8(temp16);;
	CYCLES(2);break;

case 0xa9: /**** $a9:lda $1 ****/
	temp16 = EACIMM(); CALULDA();
	CYCLES(4);break;

case 0xad: /**** $ad:lda $2 ****/
	temp16 = EACABS(); CALULDA();
	CYCLES(4);break;

case 0xae: /**** $ae:ldx $2 ****/
	temp16 = EACABS(); X = READ8(temp16);;
	CYCLES(2);break;

case 0xb1: /**** $b1:lda ($1).y ****/
	temp16 = EACINDY(); CALULDA();
	CYCLES(4);break;

case 0xb2: /**** $b2:lda ($1) ****/
	temp16 = EACIND(); CALULDA();
	CYCLES(4);break;

case 0xb5: /**** $b5:lda $1.x ****/
	temp16 = EACZEROX(); CALULDA();
	CYCLES(4);break;

case 0xb6: /**** $b6:ldx $1,y ****/
	temp16 = EACZEROY(); X = READ8(temp16);;
	CYCLES(2);break;

case 0xb9: /**** $b9:lda $2.y ****/
	temp16 = EACABSY(); CALULDA();
	CYCLES(4);break;

case 0xbd: /**** $bd:lda $2.x ****/
	temp16 = EACABSX(); CALULDA();
	CYCLES(4);break;

case 0xbe: /**** $be:ldx $2,y ****/
	temp16 = EACABSY(); X = READ8(temp16);;
	CYCLES(2);break;

case 0xc0: /**** $c0:cpy $1 ****/
	temp16 = EACIMM(); CCMP2(Y,READ8(temp16));
	CYCLES(2);break;

case 0xc1: /**** $c1:cmp $1.x ****/
	temp16 = EACABSX(); CALUCMP();
	CYCLES(4);break;

case 0xc4: /**** $c4:cpy $1 ****/
	temp16 = EACZERO(); CCMP2(Y,READ8(temp16));
	CYCLES(2);break;

case 0xc5: /**** $c5:cmp $1 ****/
	temp16 = EACZERO(); CALUCMP();
	CYCLES(4);break;

case 0xc6: /**** $c6:dec $1 ****/
	temp16 = EACZERO(); temp8 = READ8(temp16); temp8 = CDEC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0xc9: /**** $c9:cmp $1 ****/
	temp16 = EACIMM(); CALUCMP();
	CYCLES(4);break;

case 0xcc: /**** $cc:cpy $2 ****/
	temp16 = EACABS(); CCMP2(Y,READ8(temp16));
	CYCLES(2);break;

case 0xcd: /**** $cd:cmp $2 ****/
	temp16 = EACABS(); CALUCMP();
	CYCLES(4);break;

case 0xce: /**** $ce:dec $2 ****/
	temp16 = EACABS(); temp8 = READ8(temp16); temp8 = CDEC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0xd1: /**** $d1:cmp ($1).y ****/
	temp16 = EACINDY(); CALUCMP();
	CYCLES(4);break;

case 0xd2: /**** $d2:cmp ($1) ****/
	temp16 = EACIND(); CALUCMP();
	CYCLES(4);break;

case 0xd4: /**** $d4:cpy $1.x ****/
	temp16 = EACZEROX(); CCMP2(Y,READ8(temp16));
	CYCLES(2);break;

case 0xd5: /**** $d5:cmp $1.x ****/
	temp16 = EACZEROX(); CALUCMP();
	CYCLES(4);break;

case 0xd6: /**** $d6:dec $1.x ****/
	temp16 = EACZEROX(); temp8 = READ8(temp16); temp8 = CDEC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0xd9: /**** $d9:cmp $2.y ****/
	temp16 = EACABSY(); CALUCMP();
	CYCLES(4);break;

case 0xdd: /**** $dd:cmp $2.x ****/
	temp16 = EACABSX(); CALUCMP();
	CYCLES(4);break;

case 0xde: /**** $de:dec $1.y ****/
	temp16 = EACABSX(); temp8 = READ8(temp16); temp8 = CDEC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0xe0: /**** $e0:cpx $1 ****/
	temp16 = EACIMM(); CCMP2(X,READ8(temp16));
	CYCLES(2);break;

case 0xe1: /**** $e1:sbc $1.x ****/
	temp16 = EACABSX(); CALUSBC();
	CYCLES(4);break;

case 0xe4: /**** $e4:cpx $1 ****/
	temp16 = EACZERO(); CCMP2(X,READ8(temp16));
	CYCLES(2);break;

case 0xe5: /**** $e5:sbc $1 ****/
	temp16 = EACZERO(); CALUSBC();
	CYCLES(4);break;

case 0xe6: /**** $e6:inc $1 ****/
	temp16 = EACZERO(); temp8 = READ8(temp16); temp8 = CINC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0xe9: /**** $e9:sbc $1 ****/
	temp16 = EACIMM(); CALUSBC();
	CYCLES(4);break;

case 0xea: /**** $ea:nop ****/
	{};
	CYCLES(3);break;

case 0xec: /**** $ec:cpx $2 ****/
	temp16 = EACABS(); CCMP2(X,READ8(temp16));
	CYCLES(2);break;

case 0xed: /**** $ed:sbc $2 ****/
	temp16 = EACABS(); CALUSBC();
	CYCLES(4);break;

case 0xee: /**** $ee:inc $2 ****/
	temp16 = EACABS(); temp8 = READ8(temp16); temp8 = CINC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0xf1: /**** $f1:sbc ($1).y ****/
	temp16 = EACINDY(); CALUSBC();
	CYCLES(4);break;

case 0xf2: /**** $f2:sbc ($1) ****/
	temp16 = EACIND(); CALUSBC();
	CYCLES(4);break;

case 0xf5: /**** $f5:sbc $1.x ****/
	temp16 = EACZEROX(); CALUSBC();
	CYCLES(4);break;

case 0xf6: /**** $f6:inc $1.x ****/
	temp16 = EACZEROX(); temp8 = READ8(temp16); temp8 = CINC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;

case 0xf9: /**** $f9:sbc $2.y ****/
	temp16 = EACABSY(); CALUSBC();
	CYCLES(4);break;

case 0xfd: /**** $fd:sbc $2.x ****/
	temp16 = EACABSX(); CALUSBC();
	CYCLES(4);break;

case 0xfe: /**** $fe:inc $1.y ****/
	temp16 = EACABSX(); temp8 = READ8(temp16); temp8 = CINC(temp8); WRITE8(temp16,temp8);;
	CYCLES(2);break;


