#
#	This file is automatically generated.
#
class HPLCRuntime(object):
	def getCode(self):
		return [33,0,16,33,15,16,49,0,240,195,9,16,118,24,253]

	def getRoutines(self):
		return {
			"system.halt":0x100c,
			"base.address":0x1000
		}
